// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgs4POZcEb5jeZ_7hVjkG7Tx-BOv2HSQY',
    appId: '1:210781595244:web:cc0051ca465c257e711a49',
    messagingSenderId: '210781595244',
    projectId: 'listenify-app',
    authDomain: 'listenify-app.firebaseapp.com',
    storageBucket: 'listenify-app.appspot.com',
    measurementId: 'G-G9LM6QCSF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVymaGgj_jxhBEurY64B1bKl6oeg1uqk8',
    appId: '1:210781595244:android:6507c5abe868ad45711a49',
    messagingSenderId: '210781595244',
    projectId: 'listenify-app',
    storageBucket: 'listenify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_-8PpuI2VsmRgjSRx2SeLaf4cTnEmY2E',
    appId: '1:210781595244:ios:8b7fc183e2cb504d711a49',
    messagingSenderId: '210781595244',
    projectId: 'listenify-app',
    storageBucket: 'listenify-app.appspot.com',
    iosBundleId: 'com.elhazin.listen',
  );

}