// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gnhHj716Ud1hAP3QADEfURUxhO-6JMA',
    appId: '1:90482532401:web:abf80b98bf7cf47f55f510',
    messagingSenderId: '90482532401',
    projectId: 'elhazin2001',
    authDomain: 'elhazin2001.firebaseapp.com',
    storageBucket: 'elhazin2001.appspot.com',
    measurementId: 'G-QYY8BJN5GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0LDn9ZHjp1H2gre6m9dcKPrtddJIO48',
    appId: '1:90482532401:android:f424901814355af055f510',
    messagingSenderId: '90482532401',
    projectId: 'elhazin2001',
    storageBucket: 'elhazin2001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcLDkKbICKGWTmfK_qEYSj2f5R0Z_WZA',
    appId: '1:90482532401:ios:01c0cb793e21a17e55f510',
    messagingSenderId: '90482532401',
    projectId: 'elhazin2001',
    storageBucket: 'elhazin2001.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcLDkKbICKGWTmfK_qEYSj2f5R0Z_WZA',
    appId: '1:90482532401:ios:01c0cb793e21a17e55f510',
    messagingSenderId: '90482532401',
    projectId: 'elhazin2001',
    storageBucket: 'elhazin2001.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );
}
